#ifndef QTPLUGINDEMO_GLOBAL_H
#define QTPLUGINDEMO_GLOBAL_H

#if defined(QTPLUGINDEMO_LIBRARY)
#  define QTPLUGINDEMO_EXPORT Q_DECL_EXPORT
#else
#  define QTPLUGINDEMO_EXPORT Q_DECL_IMPORT
#endif

#endif // QTPLUGINDEMO_GLOBAL_H
