#ifndef QTLIBSTATICDEMO_GLOBAL_H
#define QTLIBSTATICDEMO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTLIBSTATICDEMO_LIBRARY)
#  define QTLIBSTATICDEMO_EXPORT Q_DECL_EXPORT
#else
#  define QTLIBSTATICDEMO_EXPORT Q_DECL_IMPORT
#endif

#endif // QTLIBSTATICDEMO_GLOBAL_H
